### ISSUE TITLE
Rummy Crash

### ISSUE THREAD

**Issue by raggroupkathleen** [always-on/always#250] opened 2014-02-04 20:40 UTC
Rummy crashed right at the start of the game, after the explained the rules. I made the first move and dragged the card by the pile. See google drive "rummy crash"

**Comment by charlesrich** [comment] 2014-02-05 11:57
@raggroupkathleen 

@mbehrooz, I am also sending you this, though it may also have been fixed in your merge today.  I am not sure about whether this log is for this issue or #251: https://www.dropbox.com/s/7uakqbqc0l29cpd/Rummy%20Crash.test
https://www.dropbox.com/s/7uakqbqc0l29cpd/Rummy%20Crash.test

**Comment by mbehrooz** [comment] 2014-02-06 16:42
Same as 251, this must be caused by the bug (I can tell from the log that it was during that bug).

**Closed as completed** 2014-02-06 17:54 UTC
Labels: Plugin:Rummy, Severity:Crash, Assign:BEHROOZ
