### ISSUE TITLE
Rummy Crash

### ISSUE THREAD

**Issue by raggroupkathleen** [always-on/always#263] opened 2014-02-06 17:51 UTC
Rummy froze when began playing and picked up card. See Google Drive.

**Comment by charlesrich** [comment] 2014-02-06 17:58
See log at:

https://drive.google.com/file/d/0B_Z50swri606emxNSWFUODRTWjQ/edit?usp=sharing

**Comment by charlesrich** [comment] 2014-05-22 12:52
@mbehrooz this looks like an old crash that was never assigned to you.

It looks like the client crashed.  Please see if you can reproduce this or confirm it as something you already fixed.

Tx, -CR

**Comment by mbehrooz** [comment] 2014-05-22 15:21
The date goes back to when there were some known bugs that I later fixed for my user study, specifically this kind of behavior was one of them, so I would say by 99% confidence that this is already resolved.

**Closed as completed** 2014-05-22 15:22 UTC
Labels: Plugin:Rummy, Severity:Crash, Assign:BEHROOZ
